import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/index"
import Chatbot from "@/components/Ai/chatbot"
import { Toaster, toast } from 'sonner';





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  // console.log(user);
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900`}
      >
        <Nav />
        <Toaster
          position="top-center"
          theme="dark"
          expand={true}
          toastOptions={{
            style: {
              background: "#1a1a1a",
              border: "1px solid rgba(255,255,255,0.1)",
              color: "white",
              borderRadius: "14px",
              padding: "14px 18px",
              fontSize: "15px",
              display: "flex",
              alignItems: "center",
            },
            className: "shadow-lg backdrop-blur-md",
          }}
        />
        <Chatbot />
        {children}
      </body>
    </html>
  );
}
