import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/index"
import Chatbot from "@/components/Ai/chatbot"
import { Toaster, toast } from 'sonner';





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  // console.log(user);
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900`}
      >
        <Nav />
        <Toaster />
        <Chatbot />
        {children}
      </body>
    </html>
  );
}
